extends: airbnb-base
env:
  node: true
  jest: true
plugins: [ "smells" ]
rules:
  arrow-body-style: off
  no-console: 2
  no-multiple-empty-lines: 2
  no-param-reassign: [ 2, { props: false } ]
  no-underscore-dangle: ["error", { "allow": ["__Rewire__", "__ResetDependency__", "__GetDependency__"] }]
  smells/no-complex-switch-case: 1
  smells/no-switch: 0
  smells/no-this-assign: 2